version: "2"

services:
  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
      - default
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kottu
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./docker/dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
  php:
    image: php:5.6-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - internal

networks:
  internal:
    driver: bridge
