<div class="span9">

	<legend>Clicks and posts over last 24 hours</legend>
	<div id="clickpostchart"></div>
	
	<legend>Top clickers (last 24 hours)</legend>
    <table class="table table-condensed">
    <thead><tr>
    <th>IP Address</th>
    <th>Count</th>
    </tr></thead>
    <tbody>
    <?php foreach($this->clickers as $c): ?>
    <tr>
    <td><?= $c['ip']; ?></td>
    <td><?= $c['count']; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    </table>

	<legend>Post breakdown by language</legend>
	<div id="langchart"></div>
    
    <legend>Popular blogs last month</legend>
    <table class="table table-condensed">
    <thead><tr>
    <th>Blog ID</th>
	<th>Name</th>
	<th>URL</th>
	<th># of posts</th>
	<th>Avg. buzz</th>
    </tr></thead>
    <tbody>
    <?php foreach($this->popblogs as $b): ?>
    <tr>
    <td><a target="_blank" href="<?= config('basepath'), '/blog/', $b['bid'], '" id="', $b['bid'], '">', $b['bid'] ?></a></td>
    <td><?= $b['name'] ?></td>
    <td><a target="_blank" href="<?= $b['url'] ?>"><?= $b['url'] ?></a></td>
    <td><?= $b['posts']; ?></td>
    <td><?= $b['buzz']; ?>%</td>
    </tr>
    <?php endforeach; ?>    
    </tbody>
    </table>
    
    <legend>Buzz generated by their latest posts</legend>
	<div id="recbuzzchart"></div>
    
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Language');
		data.addColumn('number', 'Posts');
		data.addRows(5);
		data.setValue(0, 0, 'English');
		data.setValue(0, 1, <?= $this->langs['en'] ?>);
		data.setValue(1, 0, 'Sinhala');
		data.setValue(1, 1, <?= $this->langs['si'] ?>);	
		<?php if($this->langs['ta'] > 0): ?>
		data.setValue(2, 0, 'Tamil');
		data.setValue(2, 1, <?= $this->langs['ta'] ?>);
		<?php endif; ?>

		var chart = new google.visualization.PieChart(document.getElementById('langchart'));
		chart.draw(data, {width: 600, height: 400, colors: ['#AE6', '#6CC', '#3B6']});
	}

	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawVisualization);
	function drawVisualization() {
		// Create and populate the data table.
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Time');
		data.addColumn('number', 'Posts');
		data.addColumn('number', 'Clicks');

		<?php foreach($this->tvalues as $key => $value): ?>
		data.addRow(['<?= ($key - 3), " - ", $key, " hours ago',", (int)(($value[0]/3)+1), ",", (int)(($value[1]/3)+1) ?>]);
		
		<?php endforeach; ?>
 
		// Create and draw the visualization.
		new google.visualization.LineChart(document.getElementById('clickpostchart')).
		draw(data, {curveType: "function",
			width: 880, height: 460,
			colors: ['#AE6', '#3B6']}
		);
	}

	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawVisualization2);
	function drawVisualization2() {
		// Create and populate the data table.
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Posts');
		<?php foreach($this->popblogs as $p): ?>
		data.addColumn('number', '<?= $p['bid'] ?>');
		<? endforeach; ?>
		
		<?php for($i = 4; $i >= 0; $i--): ?>
		data.addRow(['<?= $i ?>'<?php foreach($this->rpb as $r) { echo ', ', $r[$i]; }?> ]);
 		<? endfor; ?>
 		
		// Create and draw the visualization.
		new google.visualization.LineChart(document.getElementById('recbuzzchart')).
		draw(data, {curveType: "function",
			width: 880, height: 460,
			colors: ['#AE6', '#3B6', '#369', '#FE2', '#F90']}
		);
	}
	</script>

